/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current runtime / config status */
        get: operations["getSystem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active session diagnostics */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List built-in and custom profiles */
        get: operations["listProfiles"];
        put?: never;
        /** Create a user-defined custom profile (persisted to disk) */
        post: operations["createProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one profile's detection config */
        get: operations["getProfile"];
        /** Update an existing custom profile */
        put: operations["updateProfile"];
        post?: never;
        /** Delete a custom profile */
        delete: operations["deleteProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{name}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate a built-in or custom profile (applies detection live) */
        post: operations["activateProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List disk-backed policy files */
        get: operations["listPolicies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a policy file (with validation) */
        get: operations["getPolicy"];
        /** Create or update a policy file (validated before save) */
        put: operations["putPolicy"];
        post?: never;
        /** Delete a policy file */
        delete: operations["deletePolicy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{name}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply a policy file as active config */
        post: operations["activatePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policy/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate policy content without saving */
        post: operations["validatePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detection families, NER entity types and custom rules */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a custom regex rule */
        post: operations["createRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/rules/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update an existing custom rule */
        put: operations["updateRule"];
        post?: never;
        /** Delete a custom rule */
        delete: operations["deleteRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query / filter audit events */
        get: operations["queryAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit event counts */
        get: operations["auditSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export audit events as CSV */
        get: operations["auditExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Enhanced vault statistics */
        get: operations["vaultStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspect vault mappings (redacted by default)
         * @description Sensitive. Originals are redacted unless `reveal=true`, which additionally writes an audit event. Search on originals only applies when revealing.
         */
        get: operations["vaultMappings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminErrorBody: {
            error: {
                code: string;
                message: string;
            };
        };
        DetectionSummary: {
            secrets: boolean;
            financial: boolean;
            dates: boolean;
            emails: boolean;
            phone_numbers: boolean;
            ip_addresses: boolean;
            urls_internal: boolean;
            custom_pattern_count: number;
        };
        NerSummary: {
            enabled: boolean;
            backend: string;
            model: string | null;
            confidence_threshold: number;
            sidecar_url: string;
            entity_types: string[];
        };
        AuditSummaryInfo: {
            enabled: boolean;
            backend: string;
            location: string | null;
            log_entities: boolean;
            retention_days: number;
        };
        VaultSummary: {
            backend: string;
            path: string | null;
            persistent: boolean;
            encryption: string;
            total_mappings: number;
        };
        SystemStatus: {
            service: string;
            version: string;
            mode: string;
            listen: string;
            upstream: string;
            active_profile: string | null;
            config_path: string | null;
            policies_dir: string | null;
            profiles_dir: string | null;
            auth_required: boolean;
            masking_strategy: string;
            detection: components["schemas"]["DetectionSummary"];
            ner: components["schemas"]["NerSummary"];
            audit: components["schemas"]["AuditSummaryInfo"];
            vault: components["schemas"]["VaultSummary"];
        };
        /** @description Full detection config (mirrors cloakpipe-core DetectionConfig). */
        DetectionConfig: {
            [key: string]: unknown;
        };
        ProfileSummary: {
            name: string;
            kind: string;
            active: boolean;
            description: string;
        };
        ProfileDetail: {
            name: string;
            kind: string;
            active: boolean;
            description: string;
            detection: components["schemas"]["DetectionConfig"];
            warnings: string[];
        };
        /** @description Payload for creating or updating a user-defined custom profile. */
        CustomProfileInput: {
            /** @description Profile name. Required when creating; ignored on update (taken from the path). */
            name?: string | null;
            description?: string;
            detection: components["schemas"]["DetectionConfig"];
        };
        PolicySummary: {
            name: string;
            path: string;
            active: boolean;
            size_bytes: number;
        };
        ValidationReport: {
            valid: boolean;
            errors: string[];
            profile: string | null;
            mode: string | null;
        };
        PolicyDetail: {
            name: string;
            path: string;
            active: boolean;
            content: string;
            valid: boolean;
            validation: components["schemas"]["ValidationReport"];
        };
        PolicyContent: {
            content: string;
        };
        PolicyActivation: {
            activated: boolean;
            name: string;
            path: string;
            active_profile: string | null;
            restart_required: boolean;
            warnings: string[];
            note: string;
        };
        CustomPattern: {
            name: string;
            regex: string;
            category: string;
            value_group?: number | null;
        };
        DetectionFamily: {
            key: string;
            label: string;
            enabled: boolean;
        };
        CategoriesResponse: {
            families: components["schemas"]["DetectionFamily"][];
            ner_entity_types: string[];
            custom_rules: components["schemas"]["CustomPattern"][];
        };
        AuditEntry: {
            id: string;
            timestamp: string;
            event: string;
            surface: string;
            request_id: string | null;
            user_id: string | null;
            session_id: string | null;
            entities_detected: number | null;
            entities_replaced: number | null;
            tokens_rehydrated: number | null;
            categories: string[] | null;
        } & {
            [key: string]: unknown;
        };
        AuditEventsResponse: {
            backend: string;
            supported: boolean;
            total_matched: number;
            limit: number;
            offset: number;
            events: components["schemas"]["AuditEntry"][];
        };
        EventCount: {
            event: string;
            count: number;
        };
        AuditSummaryResponse: {
            backend: string;
            supported: boolean;
            total: number;
            counts: components["schemas"]["EventCount"][];
        };
        VaultStatsResponse: {
            backend: string;
            path: string | null;
            persistent: boolean;
            encryption: string;
            total_mappings: number;
            categories: {
                [key: string]: number;
            };
        };
        MappingEntry: {
            token: string;
            category: string;
            original: string;
            redacted: boolean;
        };
        MappingsResponse: {
            redacted: boolean;
            total_matched: number;
            limit: number;
            offset: number;
            mappings: components["schemas"]["MappingEntry"][];
            warning: string | null;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AdminErrorBody"];
            };
        };
    };
    parameters: {
        Name: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session runtime info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    listProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSummary"][];
                };
            };
        };
    };
    createProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomProfileInput"];
            };
        };
        responses: {
            /** @description Created profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetail"];
                };
            };
            400: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetail"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomProfileInput"];
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetail"];
                };
            };
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    deleteProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    activateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activated profile (with optional warnings) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetail"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    listPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicySummary"][];
                };
            };
        };
    };
    getPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDetail"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    putPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyContent"];
            };
        };
        responses: {
            /** @description Saved policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDetail"];
                };
            };
            400: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    deletePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: components["responses"]["Error"];
        };
    };
    activatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyActivation"];
                };
            };
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    validatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyContent"];
            };
        };
        responses: {
            /** @description Validation report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReport"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
        };
    };
    createRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomPattern"];
            };
        };
        responses: {
            /** @description Updated rule list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomPattern"][];
                };
            };
            400: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    updateRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomPattern"];
            };
        };
        responses: {
            /** @description Updated rule list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomPattern"][];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated rule list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomPattern"][];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    queryAuditEvents: {
        parameters: {
            query?: {
                event?: string;
                surface?: string;
                session_id?: string;
                since?: string;
                until?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventsResponse"];
                };
            };
        };
    };
    auditSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditSummaryResponse"];
                };
            };
        };
    };
    auditExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    vaultStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vault stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VaultStatsResponse"];
                };
            };
        };
    };
    vaultMappings: {
        parameters: {
            query?: {
                search?: string;
                category?: string;
                limit?: number;
                offset?: number;
                reveal?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mappings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingsResponse"];
                };
            };
        };
    };
}
